name: Keep Repository Active

on:
  schedule:
    - cron: "0 2 1 * *"   # 每月1号运行一次
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          date > .github/keepalive.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .github/keepalive.txt

          git commit -m "keep repository active" || echo "No changes"

          git push
